### ISSUE TITLE
Still getting 21.4 bits on Panopticlick.

### ISSUE THREAD

**Issue by TeddStriker** [CrisBRM/user.js#1]
Hey, I used your `user.js` file, and I have reduced my fingerprint score by a sizable margin, however, I still can't reproduce the results you have in the README. 

> Within our dataset of several million visitors, only one in **2,772,332** browsers have the same fingerprint as yours.
> 
> Currently, we estimate that your browser has a fingerprint that conveys **21.4** bits of identifying information.

Down from my browser being unique from all tested.

The problem is, even with the same addons, I don't see the `No Javascript` tags in my results. Even with `uMatrix`. Which I have been using for quit a while now. I'd love to hear more things I can do to reduce my fingerprint if you have some to share. I don't know if giving you my browser/OS details would help, so I'll just omit them unless you need them.

Thanks.

**Comment by CrisBRM** [comment]
That comes down to your default uMatrix configuration.

````	uMatrix
https-strict: * true
referrer-spoof: * true
ua-spoof: * false
* * * block
* * css allow
* * doc allow
* * frame block
* * image allow
* 1st-party frame allow

	uBlock
* * * noop
no-remote-fonts: * true````

You don't need to disable remote fonts, nor the UA spoofing rule though, that's just a personal preference (although I would advise you to). Doing so at a browser level is akin to using a hosts file and doesn't allow you to unbreak things as easily.

**Comment by TeddStriker** [comment]
Well, that's funny. I had all of that already set up. The problem was I had already white-listed the page some time ago and it overrode the global rule-set. Disabled it and got 19. The biggest culprit was my user agent, even with uMatrix spoofing, I still got a lot of bits with it, so I just used yours and got it down to 11.

>Within our dataset of several million visitors, only one in **3,288** browsers have the same fingerprint as yours.

>Currently, we estimate that your browser has a fingerprint that conveys **11.68** bits of identifying information.

This is the lowest I've ever gotten it to go, and I first found out about the test some years ago, and tried a couple of times, but to no avail. 

Thanks again.

**Comment by CrisBRM** [comment]
You're welcome! The ability to modify the HTTP_ACCEPT headers was *mostly* why I switched over from Chromium to FF (and because FF outperforms Chromium on GNU/Linux machines), since otherwise I would have had to write a small extension to spoof them.

**Comment by TeddStriker** [comment]
I tried Chromium on Windows and was willing to try it on my Linux box but it took forever to compile (like 15 hours and didn't even finish) so I decided whatever marginal performance gain it **might** have on my ancient Dell, wasn't worth it between the long compile time and the absolute lack of customization compared to Firefox. For most people it probably has a very small impact, but I'm so used to my Firefox with all its little tweaks, It'd take God knows what to happen for me to switch.

**Comment by CrisBRM** [comment]
Firefox actually outperformed it on my Funtoo, and I'm talking about Firefox (stable) vs Chromium (nightly). Chromium is roughly 10-15% faster on Windows, but extensions like uBlock, for instance, are actually more performant on FF (at least according to gorhill's multitude of benchmarks).
